// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUqIwqieBQxsqzXnWKISJSw52XLbJxWKk',
    appId: '1:330293988254:web:9d7fdff13400352b41648f',
    messagingSenderId: '330293988254',
    projectId: 'walletdz-d12e0',
    authDomain: 'walletdz-d12e0.firebaseapp.com',
    databaseURL: 'https://walletdz-d12e0-default-rtdb.firebaseio.com',
    storageBucket: 'walletdz-d12e0.appspot.com',
    measurementId: 'G-5H93D9Z5ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Dd2G-Lsj9_N6LWkjRqRBCdHd-XpFqjI',
    appId: '1:330293988254:android:89f62d7833ab772841648f',
    messagingSenderId: '330293988254',
    projectId: 'walletdz-d12e0',
    databaseURL: 'https://walletdz-d12e0-default-rtdb.firebaseio.com',
    storageBucket: 'walletdz-d12e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAie3hehD-yr_4tOGx0u94JjZL-i16-ROA',
    appId: '1:330293988254:ios:dcee21c3e8e0ef4041648f',
    messagingSenderId: '330293988254',
    projectId: 'walletdz-d12e0',
    databaseURL: 'https://walletdz-d12e0-default-rtdb.firebaseio.com',
    storageBucket: 'walletdz-d12e0.appspot.com',
    androidClientId: '330293988254-278678bv6e752ueooqkp8p21hhenflmb.apps.googleusercontent.com',
    iosClientId: '330293988254-82pfcb83vt5dccqb1po6b9s93o2kcbfq.apps.googleusercontent.com',
    iosBundleId: 'com.check.it.checkit',
  );
}
